language: python
python:
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install -r requirements.txt

script: 
  - flake8 *.py tests --exclude=ez_setup.py --max-line-length=100
  - nosetests --with-coverage --cover-package nested_dict
              --cover-inclusive --cover-min-percentage 85
  - make -C docs html
